let a = 10;
let b = 20;
console.log("a+b", a + b);
console.log("a+b", a + b);
try {
  //in try block we put all the code where there is a probabilty of error occuring
  console.log("a+b", a + c);
} catch (err) {
  //catch block is used to handle the error
  console.log(err);
}

console.log("a+b", a + b);
console.log("a+b", a + b);
console.log("a+b", a + b);
console.log("a+b", a + b);
console.log("a+b", a + b);
